// Mocks generated by Mockito 5.4.4 from annotations
// in send_money_assessment/test/domain/domain_entity_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:send_money_assessment/common/api_result.dart' as _i2;
import 'package:send_money_assessment/features/data/repository/interfaces/user_transaction_repository.dart'
    as _i3;
import 'package:send_money_assessment/features/domain/entities/user_transaction_entity.dart'
    as _i5;
import 'package:send_money_assessment/features/domain/params/user_transaction_params.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserTransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserTransactionRepository extends _i1.Mock
    implements _i3.UserTransactionRepository {
  MockUserTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.ApiResult<Map<int, dynamic>>> getAllTransactionsStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTransactionsStream,
          [],
        ),
        returnValue: _i4.Stream<_i2.ApiResult<Map<int, dynamic>>>.empty(),
      ) as _i4.Stream<_i2.ApiResult<Map<int, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.UserTransactionEntity>> getTransaction(
          _i6.UserTransactionParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransaction,
          [params],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.UserTransactionEntity>>.value(
            _FakeApiResult_0<_i5.UserTransactionEntity>(
          this,
          Invocation.method(
            #getTransaction,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.UserTransactionEntity>>);

  @override
  _i2.ApiResult<T> parseError<T>(
    _i7.DioException? e, {
    T? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseError,
          [e],
          {#data: data},
        ),
        returnValue: _FakeApiResult_0<T>(
          this,
          Invocation.method(
            #parseError,
            [e],
            {#data: data},
          ),
        ),
      ) as _i2.ApiResult<T>);
}
